### PR TITLE
Support for renaming multiple columns in the same table

### PR DESCRIPTION
**Pull request by popperur**
Fixes: https://github.com/fatkodima/online_migrations/issues/23

Adds support for renaming multiple columns in the same table.
I added a `RenamingColumnsTest` class using the existing `RenamingColumnTest` class, and tweaked the latter one a bit to make the two files look similar.

### CODE REVIEW

**Comment by popperur** [comment]
@fatkodima please let me know if you see anything to fix/change. 🙏

**Comment by fatkodima** [comment]
Thank you! ❤️ I will review it tomorrow and release a new version with it.

**Comment by fatkodima** [comment]
Thank you! I made a few small changes. Going to release a new version.

**Comment by popperur** [comment]
Awesome! 🎉

**Pull request merged**
